name: Autoremove Labels
on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]
jobs:
  RemoveNeedsTriageFromMembers:
    runs-on: ubuntu-latest
    steps:
      - name: Remove needs-triage label from member's PRs and Issues
        if: github.event.action == 'opened' && !contains( secrets.MAINTAINER_LIST, github.actor) && ${{ contains(github.event.*.labels.*.name, 'needs-triage') }}
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: 'needs-triage'
